---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-hello-vs
spec:
  hosts:
    - "nginx-hello.your.dns"
  gateways:
    - nginx-hello-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9000
        host: nginx-hello
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-hello-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "nginx-hello-local.your.dns"