---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-hello-sa
  namespace: demo

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-hello
  namespace: demo
  labels:
    app: nginx-hello
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: nginx-hello-p
  selector:
    app: nginx-hello
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
  namespace: demo
  labels:
    app: nginx-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      namespace: demo
      labels:
        app: nginx-hello
    spec:
      serviceAccountName: nginx-hello-sa
      # securityContext:
      #   runAsUser: 1000
      containers:
        - image: strm/helloworld-http
          name: 1-nginx-hello
          imagePullPolicy: Always
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   runAsUser: 1000
          resources:
            requests:
              memory: "10Mi"
              cpu: "5m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - name: nginx-hello-p
              containerPort: 80
      restartPolicy: Always
status: {}
