apiVersion: v1
kind: Service
metadata:
  name: my-internal-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: vaultwarden
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: vaultwarden